### ISSUE TITLE
Dear all,

### ISSUE THREAD

**Issue by Tranthithanhnha** [brettbode/GamessQ#15]
**Please describe the problem or enhancement:**

**If this is a bug report please list the steps required to reproduce the problem:**

**What version are you running?**

**What OS are you using? (please include 32/64 bit and if Linux the specific distribution)**

**Comment by Tranthithanhnha** [comment]
Dear all, 
I have installed gamess-64-2018-R1-pgi-mkl.msi (2018-R1-pgi-mkl | PGI 17.10 | Intel MKL 2018.1). However, as I tried to run the exam files in serials (runall.bat 2018-R1-pgi-mkl 1), all resulting exam files appear as below. I tried to reinstall but it did not work. Please give me advice how to fix it. Thank you very much.


job aborted:
[ranks] message

[0] terminated

[1] fatal error
Fatal error in MPI_Init_thread: Internal MPI error!, error stack:
MPI_Init_thread(argc_p=0x000000000014F90C, argv_p=0x000000000014FB80, required=3, provided=0x000000000014F908)
Internal MPI error!  FAIL - init called when another process has exited without calling init

---- error analysis -----

[1] on ADMIN
mpi has detected a fatal error and aborted C:\Users\Public\gamess-64\gamess.2018-R1-pgi-mkl.exe

---- error analysis -----
           Disk usage (in bytes)       
 ========================================
02/13/2018  07:42 PM             1,666 exam06.F05
04/09/2019  08:36 AM            15,278 exam06.GMS.ENV
04/09/2019  08:36 AM               121 exam06.processes.mpd
 ----------------------------------------
            Local date and time          
 ========================================
Tue 04/09/2019 -  8:36:15.09                          





--

**Comment by brettbode** [comment]
Hi,
   This is not the place to ask about problems itself, though in this case it looks more like an MPI problem. Please ask on the GAMESS users list. http://groups.google.com/group/gamess
