### ISSUE TITLE
Rejected by preprocessor

### ISSUE THREAD

**Issue by mvfbarrionuevo** [brettbode/GamessQ#5]
When running "./configure" I got these warnings:

configure: WARNING: signal.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: sys/socket.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: poll.h: accepted by the compiler, rejected by the preprocessor!

I don't have a clue about what they mean, but I would be glad to have your help guys. :)

**Comment by brettbode** [comment]
Hello,
   Can you give me a few more details? Was this with the v1.2 tarball on the download page? I just about have a v1.2.1 ready to go. You can grab a almost final copy from: https://uofi.box.com/s/xcdkplog6ekucqdjcn10gj58fdhyrjt5

Also what OS was this on?

Thanks,
Brett

**Comment by mvfbarrionuevo** [comment]
Hi,
Yes, I got those warmings with the v1.2. Thanks for sharing the newest version, but I'm afraid that won't work too. Here is what I got from v1.2 and v1.2.1 when I tried "./configure" command:

---

| Gamessq-v1.2 |
| --- |

mvfbarrionuevo@mvfbarrionuevo ~/gamessq-1.2 $ ./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for ranlib... ranlib
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking wxWidgets version... 3.0.2
checking target system type... posix
checking signal.h usability... yes
checking signal.h presence... no
configure: WARNING: signal.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: signal.h: proceeding with the compiler's result
checking for signal.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... no
configure: WARNING: sys/socket.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: sys/socket.h: proceeding with the compiler's result
checking for sys/socket.h... yes
checking poll.h usability... yes
checking poll.h presence... no
configure: WARNING: poll.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: poll.h: proceeding with the compiler's result
checking for poll.h... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: executing depfiles commands

---

| Gamessq-v1.2.1 |
| --- |

mvfbarrionuevo@mvfbarrionuevo ~/gamessq-1.2.1 $ ls
aclocal.m4    config     configure.ac  doc           INSTALL  Makefile.am  README
bundle.sh.in  configure  debian        doxygen.conf  LICENSE  Makefile.in  src
mvfbarrionuevo@mvfbarrionuevo ~/gamessq-1.2.1 $ ./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for ranlib... ranlib
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking wxWidgets version... 3.0.2
checking target system type... posix
checking signal.h usability... yes
checking signal.h presence... no
configure: WARNING: signal.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: signal.h: proceeding with the compiler's result
checking for signal.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... no
configure: WARNING: sys/socket.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: sys/socket.h: proceeding with the compiler's result
checking for sys/socket.h... yes
checking poll.h usability... yes
checking poll.h presence... no
configure: WARNING: poll.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: poll.h: proceeding with the compiler's result
checking for poll.h... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: executing depfiles commands

Besides, my linux distro is the latest fresh installed Mint 17.2.
Am I doing something wrong? I should apologize because I'm not an expert on linux. Thanks in advance. :)

**Comment by brettbode** [comment]
I am not sure if the warnings are anything to worry about. It looks like the script does create the makefile. Does a subsequent "make" succeed?

**Comment by mvfbarrionuevo** [comment]
Wow, how I was so silly! I just forgot to go on and make sure if "make" was working. For the v1.2 I got several errors when doing a "make" and "make install" commands, however with that last version you gave me (v1.2.1) everything just ran smoothly and now I can use the Gamessq. Thank you so much! I do appreciate your help :+1: . By the way, sorry for my broken English.

**Comment by mvfbarrionuevo** [comment]
Well, I got another problem now. :( Here what Gamessq showed me after fail to run a job (which I've ensured it was working through terminal):

ASSERT INFO:
../src/common/menucmn.cpp(715): assert "!IsAttached()" failed in SetInvokingWindow(): menus attached to menu bar can't have invoking window

BACKTRACE:
[1] wxMenuBase::SetInvokingWindow(wxWindow_)
[2] wxWindowBase::PopupMenu(wxMenu_, int, int)
[3] wxAppConsoleBase::CallEventHandler(wxEvtHandler_, wxEventFunctor&, wxEvent&) const
[4] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler_, wxEvent&)
[5] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler_)
[6] wxEvtHandler::TryHereOnly(wxEvent&)
[7] wxEvtHandler::ProcessEventLocally(wxEvent&)
[8] wxEvtHandler::ProcessEvent(wxEvent&)
[9] wxWindowBase::TryAfter(wxEvent&)
[10] wxScrollHelperEvtHandler::ProcessEvent(wxEvent&)
[11] wxAppConsoleBase::CallEventHandler(wxEvtHandler_, wxEventFunctor&, wxEvent&) const
[12] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler_, wxEvent&)
[13] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler_)
[14] wxEvtHandler::TryHereOnly(wxEvent&)
[15] wxEvtHandler::ProcessEventLocally(wxEvent&)
[16] wxEvtHandler::ProcessEvent(wxEvent&)
[17] wxEvtHandler::SafelyProcessEvent(wxEvent&)
[18] g_closure_invoke
[19] g_signal_emit_valist
[20] g_signal_emit
[21] gtk_propagate_event
[22] gtk_main_do_event
[23] g_main_context_dispatch
[24] g_main_loop_run
[25] gtk_main
[26] wxGUIEventLoop::DoRun()
[27] wxEventLoopBase::Run()
[28] wxAppConsoleBase::MainLoop()
[29] GamessQApp::OnRun() /home/mvfbarrionuevo/gamessq-1.2.1/src/gamessq.cpp:323
[30] wxEntry(int&, wchar_t**)
[31] main /home/mvfbarrionuevo/gamessq-1.2.1/src/gamessq.cpp:53
[32] __libc_start_main
[33] _start

**Comment by brettbode** [comment]
Hmm... Ok that one is likely to take me longer to figure out. Is this completely reproducible? Are you able to get any jobs to run?

**Comment by mvfbarrionuevo** [comment]
Yes. when I submit any job I always get the same error message coming from a popped up window. I'm going to show down here some prints I made of what I saw:

First, I got an error when submitting a job:

![screenshot from 2015-07-25 09 55 06](https://cloud.githubusercontent.com/assets/13350032/8889533/3adb53c8-32b4-11e5-8b68-77c5f923ef25.png)

Second, a window showing the error message pops up after right click on the error status:

![screenshot from 2015-07-25 09 55 53](https://cloud.githubusercontent.com/assets/13350032/8889538/50d52b9a-32b4-11e5-8673-371d6d72e9ca.png)

Finally, I have checked it out to see if I've set up the Gamess path (which seems to be ok):

![screenshot from 2015-07-25 09 56 26](https://cloud.githubusercontent.com/assets/13350032/8889542/aa1dbd20-32b4-11e5-8002-258814961a99.png)

Well, I think that's it. I'm very glad to have your help. Thank you. :)

**Comment by brettbode** [comment]
That information will likely help track that bug down.I am actually traveling the next few days so may not be able to do much with this for a week.

In the mean time one other thing might be something with the rungms or gms scripts. It would be worth testing these:
https://uofi.box.com/s/nanqhq13kvaybfneourr6ift4jbxtdmq
and
https://uofi.box.com/s/y1ymkd10w8jp2eqg08xcpmpyusesg28v

Those are ones I am going to include with the update. It seems like your gamess runs are failing to start in some way so if those happen to fix that then it might workaround this bug. Note you will need to edit the gms script to set the version information for your GAMESS binary.

**Comment by mvfbarrionuevo** [comment]
Hello again brettbode,

I made exactly what you told me with those files (rungms and gms ones) and my job ran as it should. I think everything is working now as it is supposed to. There is no problems anymore, and I hope I'm not going to bother you again. Thank you so much!

**Comment by brettbode** [comment]
Ok great! It sounds like the code is working ok when the tasks run successfully, but there must be bug in how an error case is handled. Hopefully I can track it down so there aren't cascading failures.

Thanks,
Brett

**Comment by brettbode** [comment]
Hello mvfbarrionuevo,
  I believe I have corrected the bug causing the assertion that you noted. I have posted a new 1.2.1 build at https://uofi.box.com/s/onpncpd6mk3bf8lbf7gjnrfszl9z7cqs

That is the only change so if you aren't running into the issue there is no compelling reason to update.

Best,
Brett

**Comment by mvfbarrionuevo** [comment]
Hi Brett,

I didn't get any issues since my last post, so I thank you for this new version, though I'm not going to use it right now. I'm happy to have had your help, thanks very much!

Kindest regards, 
Manoel.
