### ISSUE TITLE
Several compiling fails due to wxWidgets version

### ISSUE THREAD

**Issue by davidsousarj** [brettbode/GamessQ#7]
I have wxWidgets 2.8.12.1 installed. I get some errors with the `make` command, which I think is due to the wxWidgets version.

Firstly, I get error in resources.cpp, lines 32 and 83:

```
wxStandardPaths & gStdPaths = wxStandardPaths::Get();
```

I could fix it changing the lines to:

```
wxStandardPathsBase & gStdPaths = wxStandardPaths::Get();
```

Then I run `make` again and I get error in configuration_dialog.cpp:

```
// GetParent()->AddPendingEvent(okEvent);
GetParent()->ProcessWindowEvent(okEvent);
```

I could fix it by uncommenting the first line and commenting the second one.

And then I get multiple errors in gamessq.cpp, at the lines 340, 421, 437, 447, and 540. So I realized that it would be better if I have a really working installer, instead of having to fix by myself every incompatibility errors. After all, which is the correct wxWidgets version I am supposed to have, in order to install gamessQ correctly? Could the developers make a version of the installer compatible with wxWidgets 2.8?

**Comment by brettbode** [comment]
Hello David,
   I had just realized that some of the recent changes made the code depend on wxWidgets 3.0 or later. I was considering whether it was necessary to support wx 2.8, but I will look into it further.

Best,
Brett

**Comment by brettbode** [comment]
Hello David,
   I have checked in changes that should restore the ability to build against wxWidgets 2.8. It appears to work in some very brief testing. Are you building from the git repo or from a downloaded tar file?

Brett

**Comment by davidsousarj** [comment]
I'm using a downloaded tar file.

**Comment by brettbode** [comment]
David,
   You can grab a tarball of the current code from:
https://uofi.box.com/s/7i21an0jrraewv2qnbfhw2w4onrqv4gr

Brett

**Comment by brettbode** [comment]
I believe this issue is resolved, though I no longer regularly test against wx 2.8.
